### ISSUE TITLE
Keep functionalitity based on week, day, hour and not just on absolute creation order

### ISSUE THREAD

**Issue by jlanza** [nachoparker/btrfs-sync#1]
When using the keep option, how does it work? Could you please extend the documentation. For instance if I have daily backups and weekly backups, I would like to differentiate how keep is leaving stuff, for instance keep all weekly backups for the month but delete the daily ones, or so. This is quite difficult to achieve with the current absolute counter.
Just a suggestion for improvements,

**Comment by nachoparker** [comment]
Yes, that would be interesting, but I don't see an easy way of doing that. How would you propose we tell apart each different _kind_ of snapshot?

Thanks for your suggestions

**Comment by jlanza** [comment]
I think based on the name of the folder which if I understood correctly is daily, weekly, etc. you can filter them out. Then the name is appended with the date. Then you can easily order them just by name or splitting in name + date. I think it is like making ` find /path/to/files/ -type d -name 'daily*' -mtime +X -exec rm {} ;` where X is the number of days.

Could be like that?

**Comment by nachoparker** [comment]
I think that the cleanest way to achieve what you want is to have different snapshot folders for different "tags" (week, day...).

Then you can use `btrfs-sync` with different `keep` parameters to sync the snapshot folders with different values.
