### ISSUE TITLE
Multiple execution at the same time

### ISSUE THREAD

**Issue by mritzmann** [nachoparker/btrfs-sync#10]
Hi!

I would like to backup several clients at the same time. This can be useful, for example, if the bandwidth and CPU of the clients is limited, but the backup server and bandwidth is not utilized at all. So I could significantly increase the speed until all snapshots of all clients are transferred.

https://github.com/nachoparker/btrfs-sync/blob/6d3c3f04b5ea1bde1d063048267dc449bf98629e/btrfs-sync#L131-L132

In the bash script I found the above line which prevents simultaneous running.

So my question is: Is this a precautionary measure to protect the user, or are there technical reasons why the script should only run once at the same time?

Have a nice weekend
Markus

**Comment by nachoparker** [comment]
Hi,

Basically I don't want very long transfers scheduled with cron to overlap with each other. Say we sync every hour, and a long transfer takes 2 hours...

**Comment by mritzmann** [comment]
Hi, thanks for your answer.

In my case, I pull the snapshot.

```shell
$ btrfs-sync root@external-client01:/snapshot/ /backup-pool/external-client01
```

In this case it works best if I remove the lines mentioned in my first post. :-)
