### ISSUE TITLE
"Remote user requires sudo privileges" error

### ISSUE THREAD

**Issue by riesenstiefel** [nachoparker/btrfs-sync#18]
Hi,

this script used to work like a charm for me, but the latest commit keeps failing with
`Remote user requires sudo privileges`

I followed [Nachos instructions](https://ownyourbits.com/2018/03/09/easy-sync-of-btrfs-snapshots-with-btrfs-sync/) (again, just to be sure).

When on my sending machine I call
`ssh -p 22 -o ServerAliveInterval=5 -o ConnectTimeout=1 -o BatchMode=yes btrfs@<dest-host> sudo echo`
which is just what the following line does
https://github.com/nachoparker/btrfs-sync/blob/5647f149ecdb52861b7c3498b8324e16d53ee8bc/btrfs-sync#L139
I get
```

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
```

On my receiving machine:
```bash
sudo cat /etc/sudoers.d/90_btrfs-sync
btrfs ALL=(root:nobody) NOPASSWD:NOEXEC: /bin/btrfs
```

If I comment the following lines, snapshot syncing works again:
https://github.com/nachoparker/btrfs-sync/blob/5647f149ecdb52861b7c3498b8324e16d53ee8bc/btrfs-sync#L135-L139

**Comment by nachoparker** [comment]
ok, then let's revert, until we have a version that doesn't break things

cc @jenszo
