### ISSUE TITLE
empty stream is not considered valid error when syncing snapshot

### ISSUE THREAD

**Issue by skymoo** [nachoparker/btrfs-sync#3]
I'm using `btrfs-snp` and `btrfs-sync` in cron with basically the following:

```
btrfs-snp /home hourly 24 3600
btrfs-snp /home daily 7 86400
btrfs-snp /home weekly 4 604800
btrfs-snp /home monthly 12 2592000
btrfs-snp / daily 14 86400

btrfs-sync -d /home/.snapshots /path/to/external/drive/home
btrfs-sync -dv /.snapshots /path/to/external/drive/root
```

When syncing more than one daily snapshot of my root filesystem I'm getting the following error:

```
* Check source
* Check destination
* Skip existing '/.snapshots/daily_2019-03-04-131702'
* Synchronizing '/.snapshots/daily_2019-03-05-141702' using seed '@/.snapshots/daily_2019-03-04_131702'...
ERROR: not on mount point: /
time elapsed [0:00:00] | rate [0.00 B/s] | total size [0.00 B]
ERROR: empty stream is not considered valid
```

There are no issues with syncing multiple snapshots of the home filesystem, just root.

I am doing something wrong?

**Comment by skymoo** [comment]
Could this be: https://github.com/kdave/btrfs-progs/pull/138

**Comment by nachoparker** [comment]
it does look like that, maybe try with a newer btrfs-tools

**Comment by skymoo** [comment]
That is indeed the problem, installing the latest `btrfs-tools` allows the snapshot to be synced correctly.
