### ISSUE TITLE
shouldn't need to be run via sudo

### ISSUE THREAD

**Issue by vasyugan** [nachoparker/btrfs-sync#6]
The instructions for setting up btrfs-sync say that you should give the btrfs user sudo permission on both the host and the target machines. 
When this is done, the script could all the btrfs commands via sudo rather than requiring that the entire script is run via sudo. Else, what's the point?
If the entire script is to be run via sudo, then of course, you must give sudo permissions for /usr/local/bin/btrfs-sync, rather than the btrfs command
But when I run the script via sudo, it fails after the getopt command in line 77. I removed the > /dev/null to see what is going on,  and I found that there is a "getopt: no permission" message, which is strange. What permission would getopt even need?

Also, when I run the script as root, then the ssh command is executed as root as well so that on the target machine, root's pubkey has to be added to ~btrfs/.ssh/authorized_keys

Anyway, I guess the script should be modified so that all btrfs commands are done via sudo, so that the entire script does not have to be run as root.

**Comment by halvors** [comment]
+1

**Comment by nachoparker** [comment]
The script manages subvolumes, which requires `root` privileges, so I think that requiring the whole script to be ran as `root` is the most appropriate here.

The `sudo` command has a whole lot of ramifications and possible configs/uses that don't concern `btrfs-sync`

Thanks!
