### ISSUE TITLE
Is there an option for two-way sync?

### ISSUE THREAD

**Issue by typoworx-de** [nachoparker/btrfs-sync#7]
I would like to synchronize some btrfs-subvolumes in two-way, meaning I have Computer A and Computer B both having "shared" data stored on btrfs-subvolumes. I don't want to sync one-way as on Computer B there may be changes I also want on Computer A instead of overriding them (and vice-versa). Is there some option or any other solution to handle this?

**Comment by nachoparker** [comment]
hi,

BTRFS is able to sync snapshots, but that doesn't fit into what you are trying to achieve. You would be better off with something like rsync
